### PR TITLE
feature: add worker_filter option to Boundary Credential Store Vault

### LINKED ISSUE #294: boundary_credential_store_vault worker_filter needed
The resource boundary_credential_store_vault needs worker_filter option

### Terraform Version
+ provider registry.terraform.io/hashicorp/boundary v1.1.2
- Using previously-installed hashicorp/boundary v1.1.2

### Affected Resource(s)
Please list the resources as a list, for example:
boundary_credential_store_vault 

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
resource "boundary_credential_store_vault" "foo" {
  provider = boundary.hcpboundary   
  name        = "foo"
  description = "My first Vault credential store!"
  address     = "https://vault-cluster-private-<removed>.hashicorp.cloud:8200"      # change to Vault address
  namespace   = "admin"
  token       = "hvs.CAESI23432<removed>AQuPkF" # change to valid Vault token
  scope_id    = boundary_scope.project.id
}

### Expected Behavior
Should be a place for worker_filter as an optional resource

### Actual Behavior
What actually happened?
No option

### PR DESCRIPTION
**Pull request by mikemountain**
Closes #294

### CODE REVIEW

**Review by johanbrandhorst — COMMENTED** [review]
Is it possible to add a test for this new variable?

**Comment by irenarindos** [comment]
> Is it possible to add a test for this new variable?

@johanbrandhorst I don't think we can, since it's an HCP only feature and depends on having a Vault instance and PKI worker up and running

**Review by irenarindos — APPROVED** [review]
Looks good! I'd just ask that you manually test it works before merging.

**Comment by mikemountain** [comment]
Manually verified 👍

**Pull request merged**
